[workspace]
members = [
    #"crates/ast/turboprisma_ast",
    "crates/turboprisma_cli",
    "crates/ast/*",
    "crates/libs/*",
    "crates/format/*",
    "crates/query_engine/*",
    "crates/turboprisma_vm"
]