[package]
name = "parser_database"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
schema_ast = { path = "../schema_ast" }

enumflags2 = "0.7"
indexmap = "1.8.0"
either = "1.6.1"
